### ISSUE TITLE
How could we pre-calculate the query for all time dockless data counts

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-and-performance#285]
The all time query takes a long to load and it will only get worse and worse over time. What are some solutions to pre-cache this query, either as a new/separate open dataset in Socrata or in some other JSON store that gets updated frequently?

**Comment by sergiogcx** [comment]
Self note (it takes 15sec to load):

http://transportation.austintexas.io/dockless-data/

![Screen Shot 2019-07-05 at 2.52.34 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/69bf25e5-fb74-40f2-bda9-e90f1a724db4)
