### ISSUE TITLE
UI tweaks

### ISSUE THREAD

**Issue by tylerwhitson** [cityofaustin/atd-data-and-performance#299]
Want to tweak the UI so that the month and date range selectors remain on the screen after you make a selection (in case, for example, the user wants to look at several months in succession without having to select "by month" multiple times.

**Comment by mateoclarke** [comment]
What's the status of this one @tcwcodes?

**Comment by mateoclarke** [comment]
If its related to PR #300, can you make sure to link it? And if we don't want to merge that feature, can you close the PR?

**Comment by tcwcodes** [comment]
I didn’t end up implementing it but may want to in the future. Would it be
appropriate to stash it in an icebox?

**Comment by mateoclarke** [comment]
sure, Icebox is ok.
