### ISSUE TITLE
ETL: Signal Timing and Phasing Data

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-and-performance#305]
In order to be able to visualize signal timing and phasing data we need to work on the data infrastructure required to make the data public.

https://github.com/cityofaustin/transportation.austintexas.io/issues/268

This data current lives on the KITS app server database, which is an MSSQL server called KITSDB

**Comment by johnclary** [comment]
Jen has asked us to prioritize this. I'm hoping @sergiogcx or @mddilley has bandwidth mid-january.

cc @amenity

**Comment by amenity** [comment]
Might apply to https://github.com/cityofaustin/atd-knack-data-tracker/issues/241

**Comment by amenity** [comment]
@johnclary @mateoclarke should we tee this up for Sprint 17?

**Comment by johnclary** [comment]
@amenity i just kicked it to sprint 18.

**Comment by amenity** [comment]
Sprint 19, @mateoclarke @johnclary ?

**Comment by johnclary** [comment]
I've dropped the milestone from this list and put a [new dependency](https://github.com/cityofaustin/atd-data-tech/issues/1469) in front of it. Will reaching out as this progresses.
