### ISSUE TITLE
Operations Overview Signals Retimed widget displays "NaN"

### ISSUE THREAD

**Issue by tcwcodes** [cityofaustin/atd-data-and-performance#323]
https://transportation.austintexas.io/ops-overview/

Signals Re-Timed widget displays "NaN"

**Comment by TracyLinder** [comment]
@tcwcodes Can you assign somebody to this card, add a description, and move it to the correct pipeline please?

**Comment by tcwcodes** [comment]
> @tcwcodes Can you assign somebody to this card, add a description, and move it to the correct pipeline please?

Thanks @TracyLinder, it's assigned to me, I elaborated on the description and moved it to "On Deck."

**Comment by amenity** [comment]
@tcwcodes What's the status of this issue? Will you be working on it next week, or should we stick it in the backlog?

**Comment by tcwcodes** [comment]
> @tcwcodes What's the status of this issue? Will you be working on it next week, or should we stick it in the backlog?

I did some troubleshooting on this issue on Friday and determined what's causing it. I just need to find a suitable solution and then will submit a PR! Working on this between other projects but am hoping to submit a PR this week or Monday.

**Comment by amenity** [comment]
@tcwcodes thanks! Estimate-wise, are we thinking days/3?

**Comment by tcwcodes** [comment]
I added an estimate (2/hours) and submitted the PR!
