### ISSUE TITLE
Update transportation-data references on dashboards

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-and-performance#328]
A number of dashboards pull data from `transportation-data.austintexas.io`. These URLs need to be updated to use this base url: `http://transportation-data-01-58741847.us-east-1.elb.amazonaws.com`.

Here's a search to bring up the affected lines of code:
https://github.com/cityofaustin/transportation.austintexas.io/search?q=transportation-data.austintexas.io&unscoped_q=transportation-data.austintexas.io

**Comment by johnclary** [comment]
@mateoclarke @tcwcodes  can y'all get this done on monday? we'll have to replace these again once `austintexas.io` or `austinmobility.io` come online.

**Comment by tcwcodes** [comment]
Will make it my top priority!

**Comment by tcwcodes** [comment]
PR submitted!
